name: Java CI

# Trigger the workflow on every push and pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up the Java version
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'   # Specify the Java version you need
          distribution: 'temurin'
          cache: maven

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        run: mvn -B package --file pom.xml

      # Build and test the project with Maven
      - name: Build with Maven
        run: mvn clean verify

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
